django_jugadores/apps/crudjugadores/urls.py
from django.conf.urls import url
from apps.crudjugadores.views import JugadorCreate, JugadorList, JugadorDelete, JugadorUpdate, JugadorShow, search

urlpatterns = [
    url(r'^nuevo/', JugadorCreate.as_view(), name='jugador_crear'),
    url(r'^listar', JugadorList.as_view(), name='jugador_listar'),
    url(r'^eliminar/(?P<pk>\d+)/$', JugadorDelete.as_view(), name='jugador_eliminar'),
    url(r'^editar/(?P<pk>\d+)/$', JugadorUpdate.as_view(), name='jugador_editar'),
    url(r'^mostrar/(?P<pk>\d+)/$', JugadorShow.as_view(), name='jugador_mostrar'),
    url(r'^buscar/$', search, name='jugador_buscar'),
]

django_jugadores/jugadores/urls.py
from django.conf.urls import url, include

from apps.crudjugadores import admin

urlpatterns = [
    url(r'^jugadores/', include('apps.crudjugadores.urls', namespace='jugadores')),
    #url(r'^admin/', include(admin.site.urls)),


]

django_jugadores/apps/crudjugadores/models.py
from django.db import models

# Create your models here.
class Deporte(models.Model):
	id = models.IntegerField(primary_key=True)
	nombre = models.CharField(max_length=20)

	def __str__(self):
		return '{}'.format(self.nombre)

class Jugador(models.Model):
	id = models.IntegerField(primary_key=True)
	nombres = models.CharField(max_length=50)
	apellidos = models.CharField(max_length=50)
	fecha_nacimiento = models.DateField()
	email = models.CharField(max_length=50)
	deporte = models.ForeignKey(Deporte, null=True, blank=True, on_delete=models.CASCADE)

django_jugadores/crudjugadores/models.py
from django.db import models

# Create your models here.

django_jugadores/apps/crudjugadores/forms.py
from django import forms
from apps.crudjugadores.models import Jugador

class JugadorForm(forms.ModelForm):
	class Meta:
		model = Jugador
		fields = [
			'id',
			'nombres',
			'apellidos',
			'fecha_nacimiento',
			'email',
			'deporte',
		]

		labels = {
			'id': 'Identificacion',
			'nombres': 'Nombres',
			'apellidos': 'Apellidos',
			'fecha_nacimiento': 'Fecha de Nacimiento',
			'email': 'Correo Electronico',
			'deporte': 'Deporte',
		}

		widgets = {
			'id': forms.TextInput(attrs={'class':'form-control'}),
			'nombres': forms.TextInput(attrs={'class':'form-control'}),
			'apellidos': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_nacimiento': forms.TextInput(attrs={'class':'form-control'}),
			'email': forms.TextInput(attrs={'class':'form-control'}),
			'deporte': forms.Select(attrs={'class':'form-control'}),
		}

django_jugadores/apps/crudjugadores/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy
from django.views.generic.detail import DetailView

from apps.crudjugadores.models import Jugador
from apps.crudjugadores.forms import JugadorForm
from apps.crudjugadores.filters import JugadorFilter

# Create your views here.

class JugadorCreate(CreateView):
	model = Jugador
	form_class = JugadorForm
	template_name = 'crudjugadores/jugador_form.html'
	success_url = reverse_lazy('jugadores:jugador_listar')


class JugadorList(ListView):
	queryset = Jugador.objects.order_by('id')
	template_name = 'crudjugadores/jugadores_list.html'
	paginate_by = 5

class JugadorUpdate(UpdateView):
	model = Jugador
	form_class = JugadorForm
	template_name = 'crudjugadores/jugador_form.html'
	success_url = reverse_lazy('jugadores:jugador_listar')

class JugadorDelete(DeleteView):
	model = Jugador
	template_name = 'crudjugadores/jugador_delete.html'
	success_url = reverse_lazy('jugadores:jugador_listar')

class JugadorShow(DetailView):
	model = Jugador
	template_name = 'crudjugadores/jugador_show.html'

def search(request):
	jugador_list = Jugador.objects.all()
	jugador_filter = JugadorFilter(request.GET, queryset=jugador_list)
	return render(request, 'crudjugadores/jugador_list2.html', {'filter': jugador_filter})

django_jugadores/crudjugadores/views.py
from django.shortcuts import render

# Create your views here.

django_jugadores/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Document {% endblock %}</title>
</head>
<body>
<div class="container">

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="#">Home</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Jugadores <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'jugadores:jugador_crear' %}">Registrar</a></li>
				                        	<li><a href="{% url 'jugadores:jugador_listar' %}">Listar</a></li>
				                        	<li><a href="{% url 'jugadores:jugador_buscar' %}">Buscar/Filtrar</a></li>
				                        </ul>
		                      		</li>
		                    	</ul>
		                    	<ul class="nav navbar-nav navbar-right">
		                        	<li class="dropdown"><a href="https://www.facebook.com/eduardo.sandoval.752487" onclick="pageTracker._link(this.href); return false;">Conoce al Desarrollador</a>
		                        	</li>
		                        	<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
		                        		<ul class="dropdown-menu" role="menu">
		                          			<li><a href="#">Salir</a></li>
		                        		</ul>
		                      		</li>
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>    

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}


</body>
</html>

django_jugadores/templates/crudjugadores/jugador_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ object.nombres }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'jugadores:jugador_listar' %}">Cancelar</a>
</form>
{% endblock %}

django_jugadores/templates/crudjugadores/jugador_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-success" type="submit">Guardar</button>
	<a class= "btn btn-primary" href="{% url 'jugadores:jugador_listar' %}">Cancelar</a>
</form>
{% endblock %}

django_jugadores/templates/crudjugadores/jugador_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombres</td>
			<td>Apellidos</td>
			<td>Fecha de Nacimiento</td>
			<td>email</td>
			<td>Deporte</td>
			<td>Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for jugador in object_list %}
		<tr>
			<td>{{ jugador.id }}</td>
			<td>{{ jugador.nombres }}</td>
			<td>{{ jugador.apellidos }}</td>
			<td>{{ jugador.fecha_nacimiento }}</td>
			<td>{{ jugador.email }}</td>
			<td>{{ jugador.deporte }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'jugadores:jugador_mostrar' jugador.id %}">Ver</a>
				<a class="btn btn-primary" href="{% url 'jugadores:jugador_editar' jugador.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'jugadores:jugador_eliminar' jugador.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay registros de jugadores</h1>
		{% endif %}
	</tbody>
</table>
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a> 
    	{% endif %}
    </li>
</ul> 
{% endblock%}

django_jugadores/templates/crudjugadores/jugador_list2.html
{% extends 'base/base.html' %}

{% block content %}
	<h4>Filtrar por:</h4>
	<form method="get">
	<p>
	Nombre: &nbsp{{ filter.form.nombres }} &nbsp
	Apellido: &nbsp {{ filter.form.apellidos }} &nbsp
	Email: &nbsp{{ filter.form.email }} &nbsp;&nbsp;
	<button class="btn btn-success" type="submit">Filtrar</button>
	</p>
	</form>
	<table class="table table-bordered">
	<thead>
		<tr>
			<td>id</td>
			<td>Nombres</td>
			<td>Apellidos</td>
			<td>Fecha de Nacimiento</td>
			<td>email</td>
			<td>Deporte</td>
			<td>Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if filter.qs %}
		{% for jugador in filter.qs %}
		<tr>
			<td>{{ jugador.id }}</td>
			<td>{{ jugador.nombres }}</td>
			<td>{{ jugador.apellidos }}</td>
			<td>{{ jugador.fecha_nacimiento }}</td>
			<td>{{ jugador.email }}</td>
			<td>{{ jugador.deporte }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'jugadores:jugador_mostrar' jugador.id %}">Ver</a>
				<a class="btn btn-primary" href="{% url 'jugadores:jugador_editar' jugador.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'jugadores:jugador_eliminar' jugador.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay registros de jugadores</h1>
		{% endif %}
	</tbody>
</table>
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a> 
    	{% endif %}
    </li>
</ul> 
	
{% endblock %}


django_jugadores/templates/crudjugadores/jugador_show.html
{% extends 'base/base.html' %}

{% block content %}

<p><strong>identificacion: </strong>{{ object.id }} </p>
<p><strong>Nombres: </strong>{{ object.nombres }} </p>
<p><strong>Apellidos: </strong>{{ object.apellidos }} </p>
<p><strong>Fecha de Nacimiento: </strong>{{ object.fecha_nacimiento }} </p>
<p><strong>email: </strong>{{ object.email }} </p>
<p><strong>Deporte: </strong>{{ object.deporte }} </p>

<a class= "btn btn-success" href="{% url 'jugadores:jugador_listar' %}">Ok</a>
<a class= "btn btn-primary" href="{% url 'jugadores:jugador_editar' object.id%}">Editar</a>
<a class="btn btn-danger" href="{% url 'jugadores:jugador_eliminar' object.id %}">Eliminar</a>

{% endblock %}